---
name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint with flake8
        run: |
          flake8
      - name: Run tests
        run: |
          sudo apt-get install -y --no-install-recommends dexdump  # required to install exodus-core
          pip install -r requirements.txt
          python -m unittest
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
  build_image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push latest image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: exodusprivacy/exodus-standalone:latest
      - name: Build and push tag image
        if: github.event_name == 'push' && github.ref_type == 'tag'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: exodusprivacy/exodus-standalone:${{ github.ref_name }}
