---
name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint with flake8
        run: |
          flake8
      - name: Run tests
        run: |
          sudo apt-get install -y --no-install-recommends dexdump  # required to install exodus-core
          pip install -r requirements.txt
          python -m unittest
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
