---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint with flake8
        run: |
          flake8
      - name: Run tests
        run: |
          sudo apt-get install -y --no-install-recommends dexdump  # required to install exodus-core
          pip install -r requirements.txt
          python -m unittest

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile

  docker_build:
    if: github.event_name == 'pull_request'
    needs: hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: false

  docker_push:
    if: github.event_name == 'push'
    needs: hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push latest image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: exodusprivacy/exodus-standalone:latest
